// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vein360.Persistence;

#nullable disable

namespace Vein360.Persistence.Migrations
{
    [DbContext(typeof(Vein360Context))]
    [Migration("20250808031524_Added_Quantity_To_Order")]
    partial class Added_Quantity_To_Order
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vein360.Domain.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrimaryContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "CLINIC STREET LINE 1",
                            City = "HARRISON",
                            ClinicName = "ABC Clinic",
                            Country = "US",
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            PostalCode = "72601",
                            PrimaryContactPhone = "9876543210",
                            State = "AR",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "CLINIC STREET LINE 1",
                            City = "HARRISON",
                            ClinicName = "XYZ Clinic",
                            Country = "US",
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            PostalCode = "72601",
                            PrimaryContactPhone = "9876543210",
                            State = "AR",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<long?>("ContainerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("FedexTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabelFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MasterTrackingNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("TrackingNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UseOldLabel")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DonorId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0.0,
                            ClinicId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 1,
                            TrackingNumber = 1234567890L,
                            UseOldLabel = false
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0.0,
                            ClinicId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 1,
                            TrackingNumber = 1234567891L,
                            UseOldLabel = false
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0.0,
                            ClinicId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 3,
                            TrackingNumber = 1234567892L,
                            UseOldLabel = false
                        },
                        new
                        {
                            Id = 4,
                            Amount = 0.0,
                            ClinicId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 4,
                            TrackingNumber = 1234567893L,
                            UseOldLabel = false
                        },
                        new
                        {
                            Id = 5,
                            Amount = 0.0,
                            ClinicId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 1,
                            TrackingNumber = 1234567894L,
                            UseOldLabel = false
                        });
                });

            modelBuilder.Entity("Vein360.Domain.Entities.DonationContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedUnits")
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ReplenishmentOrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestedUnits")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("DonorId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("DonationContainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1001L,
                            RequestedUnits = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ApprovedUnits = 9,
                            ClinicId = 1,
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1002L,
                            RequestedUnits = 9,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            ApprovedUnits = 8,
                            ClinicId = 1,
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1003L,
                            RequestedUnits = 8,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            ApprovedUnits = 7,
                            ClinicId = 1,
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1004L,
                            RequestedUnits = 7,
                            Status = 3
                        },
                        new
                        {
                            Id = 5,
                            ApprovedUnits = 6,
                            ClinicId = 1,
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1005L,
                            RequestedUnits = 6,
                            Status = 3
                        },
                        new
                        {
                            Id = 6,
                            ApprovedUnits = 5,
                            ClinicId = 1,
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1006L,
                            RequestedUnits = 5,
                            Status = 3
                        },
                        new
                        {
                            Id = 7,
                            ApprovedUnits = 4,
                            ClinicId = 2,
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1007L,
                            RequestedUnits = 4,
                            Status = 3
                        },
                        new
                        {
                            Id = 8,
                            ApprovedUnits = 3,
                            ClinicId = 2,
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1008L,
                            RequestedUnits = 3,
                            Status = 3
                        },
                        new
                        {
                            Id = 9,
                            ApprovedUnits = 4,
                            ClinicId = 2,
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1009L,
                            RequestedUnits = 4,
                            Status = 3
                        },
                        new
                        {
                            Id = 10,
                            ApprovedUnits = 5,
                            ClinicId = 2,
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1010L,
                            RequestedUnits = 5,
                            Status = 2
                        },
                        new
                        {
                            Id = 11,
                            ApprovedUnits = 6,
                            ClinicId = 2,
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1011L,
                            RequestedUnits = 6,
                            Status = 2
                        },
                        new
                        {
                            Id = 12,
                            ApprovedUnits = 7,
                            ClinicId = 2,
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            ReplenishmentOrderId = 1012L,
                            RequestedUnits = 7,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Vein360.Domain.Entities.DonationPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.ToTable("DonationPayments");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.DonationProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accepted")
                        .HasColumnType("int");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RejectedClogged")
                        .HasColumnType("int");

                    b.Property<int>("RejectedDamaged")
                        .HasColumnType("int");

                    b.Property<int>("RejectedFunction")
                        .HasColumnType("int");

                    b.Property<int>("RejectedKinked")
                        .HasColumnType("int");

                    b.Property<int>("RejectedOther")
                        .HasColumnType("int");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.HasIndex("ProductId");

                    b.ToTable("DonationProduct");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accepted = 0,
                            DonationId = 1,
                            ProductId = 1,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 2,
                            Accepted = 0,
                            DonationId = 1,
                            ProductId = 2,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 3,
                            Accepted = 0,
                            DonationId = 1,
                            ProductId = 3,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 4,
                            Accepted = 0,
                            DonationId = 2,
                            ProductId = 1,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 5,
                            Accepted = 0,
                            DonationId = 2,
                            ProductId = 3,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 6,
                            Accepted = 0,
                            DonationId = 2,
                            ProductId = 5,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 7,
                            Accepted = 0,
                            DonationId = 3,
                            ProductId = 1,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 8,
                            Accepted = 0,
                            DonationId = 3,
                            ProductId = 4,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 9,
                            Accepted = 0,
                            DonationId = 3,
                            ProductId = 5,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 10,
                            Accepted = 0,
                            DonationId = 4,
                            ProductId = 1,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 11,
                            Accepted = 0,
                            DonationId = 4,
                            ProductId = 5,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 12,
                            Accepted = 0,
                            DonationId = 4,
                            ProductId = 2,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 13,
                            Accepted = 0,
                            DonationId = 5,
                            ProductId = 1,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 14,
                            Accepted = 0,
                            DonationId = 5,
                            ProductId = 2,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        },
                        new
                        {
                            Id = 15,
                            Accepted = 0,
                            DonationId = 5,
                            ProductId = 4,
                            RejectedClogged = 0,
                            RejectedDamaged = 0,
                            RejectedFunction = 0,
                            RejectedKinked = 0,
                            RejectedOther = 0,
                            Units = 1
                        });
                });

            modelBuilder.Entity("Vein360.Domain.Entities.DonorPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DefaultClinicId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Vein360UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultClinicId");

                    b.HasIndex("DonorId");

                    b.HasIndex("Vein360UserId");

                    b.ToTable("DonorPreferences");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Vein360ProductId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Trade");

                    b.HasIndex("Vein360ProductId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter.jpg",
                            IsDeleted = false,
                            Name = "ClosureFast Catheter",
                            Price = 1000m,
                            Trade = 1,
                            Type = 1,
                            Vein360ProductId = "CF7-3-60"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter-100B.jpg",
                            IsDeleted = false,
                            Name = "ClosureFast Catheter",
                            Price = 1800m,
                            Trade = 1,
                            Type = 1,
                            Vein360ProductId = "CF7-7-100"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "basic-procedure-pack.jpg",
                            IsDeleted = false,
                            Name = "ClosureFast Catheter, 60 cm",
                            Price = 900m,
                            Trade = 1,
                            Type = 1,
                            Vein360ProductId = "CF7-7-60"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-eagle-eye-platinum-catheter.jpg",
                            IsDeleted = false,
                            Name = "Clinically Soiled Visions PV 018",
                            Price = 2000m,
                            Trade = 1,
                            Type = 2,
                            Vein360ProductId = "86700"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "complete-procedure-pack-7f-x-7-cm-introducer-kit.jpg",
                            IsDeleted = false,
                            Name = "Clinically Soiled Visions PV 035",
                            Price = 1200m,
                            Trade = 1,
                            Type = 2,
                            Vein360ProductId = "88901"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "7F-x-7-cm-Introducer-Sheath-Kit.jpg",
                            IsDeleted = false,
                            Name = "Clinically Soiled Refinity IVUS Catheter",
                            Price = 1500m,
                            Trade = 1,
                            Type = 2,
                            Vein360ProductId = "89900"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter.jpg",
                            IsDeleted = false,
                            Name = "Clinically Soiled Visions PV014P RX",
                            Price = 1500m,
                            Trade = 1,
                            Type = 2,
                            Vein360ProductId = "014R"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter-100B.jpg",
                            IsDeleted = false,
                            Name = "Clinicially Soiled Eagle Eye Platinum",
                            Price = 1500m,
                            Trade = 1,
                            Type = 2,
                            Vein360ProductId = "85900P"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "basic-procedure-pack.jpg",
                            IsDeleted = false,
                            Name = "Clinically Soiled Eagle Eye Platinum ST",
                            Price = 1500m,
                            Trade = 1,
                            Type = 2,
                            Vein360ProductId = "85900PST"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-eagle-eye-platinum-catheter.jpg",
                            IsDeleted = false,
                            Name = "Clinically Soiled Visions 014 Platinum",
                            Price = 1500m,
                            Trade = 1,
                            Type = 2,
                            Vein360ProductId = "85910P"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "complete-procedure-pack-7f-x-7-cm-introducer-kit.jpg",
                            IsDeleted = false,
                            Name = " Clinically Soiled Ambu® aScope™ 4 Cysto, Reverse Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "600001000"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "7F-x-7-cm-Introducer-Sheath-Kit.jpg",
                            IsDeleted = false,
                            Name = " Clinically Soiled Ambu® aScope™ 4 Cysto, Standard Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "601001000"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter.jpg",
                            IsDeleted = false,
                            Name = "Clinically Soiled Ambu aScope 5 Cysto HD – Reverse Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "602001000"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter-100B.jpg",
                            IsDeleted = false,
                            Name = "Clinically Soiled Ambu aScope 5 Cysto HD – Standard Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "603001000"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "basic-procedure-pack.jpg",
                            IsDeleted = false,
                            Name = "Dornier Axis II Model E Reverse Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "AX20408"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-eagle-eye-platinum-catheter.jpg",
                            IsDeleted = false,
                            Name = "Dornier Axis II Model E Standard Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "AX20409"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "complete-procedure-pack-7f-x-7-cm-introducer-kit.jpg",
                            IsDeleted = false,
                            Name = "Dornier Axis II Cystoscope",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "AX20411"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "7F-x-7-cm-Introducer-Sheath-Kit.jpg",
                            IsDeleted = false,
                            Name = "Dornier Axis II Model D Reverse Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "AX20413"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-eagle-eye-platinum-catheter.jpg",
                            IsDeleted = false,
                            Name = "Dornier Axis II Model D Standard Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "AX20414"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter-100B.jpg",
                            IsDeleted = false,
                            Name = "Dornier Axis Ureteroscope",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "AX93US31B"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "basic-procedure-pack.jpg",
                            IsDeleted = false,
                            Name = "LithoVue Standard Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "M0067913500"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-eagle-eye-platinum-catheter.jpg",
                            IsDeleted = false,
                            Name = "LithoVue Reverse Deflection",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "M0067913600"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "complete-procedure-pack-7f-x-7-cm-introducer-kit.jpg",
                            IsDeleted = false,
                            Name = "LithoVue Empower",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "M0067919900"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "7F-x-7-cm-Introducer-Sheath-Kit.jpg",
                            IsDeleted = false,
                            Name = "LithoVue™ Elite Standard Deflection w/ pressure monitoring",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "M0067940000"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-eagle-eye-platinum-catheter.jpg",
                            IsDeleted = false,
                            Name = "LithoVue™ Elite Reverse Deflection w/ pressure monitoring",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "M0067940500"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter-100B.jpg",
                            IsDeleted = false,
                            Name = "LithoVue™ Elite Standard Deflection w/o pressure monitoring",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "M0067941000"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "complete-procedure-pack-7f-x-7-cm-introducer-kit.jpg",
                            IsDeleted = false,
                            Name = "LithoVue™ Elite Reverse Deflection w/o pressure monitoring",
                            Price = 1500m,
                            Trade = 1,
                            Type = 3,
                            Vein360ProductId = "M0067941500"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter.jpg",
                            IsDeleted = false,
                            Name = "Visions PV 018 Digital IVUS Catheter (Sterile Single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 2,
                            Vein360ProductId = "VEN-PV-018"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "basic-procedure-pack.jpg",
                            IsDeleted = false,
                            Name = "Visions PV 035 Digital IVUS Catheter (Sterile Single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 2,
                            Vein360ProductId = "VEN-PV-035"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-eagle-eye-platinum-catheter.jpg",
                            IsDeleted = false,
                            Name = "Visions 014 Platinum RX Catheter (Sterile Single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 2,
                            Vein360ProductId = "VEN-PV-014R"
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "complete-procedure-pack-7f-x-7-cm-introducer-kit.jpg",
                            IsDeleted = false,
                            Name = "Eagle Eye Platinum Catheter (Sterile Single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 2,
                            Vein360ProductId = "VEN-PV-EEP"
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "7F-x-7-cm-Introducer-Sheath-Kit.jpg",
                            IsDeleted = false,
                            Name = "Eagle Eye Platinum Short Tip Catheter (Sterile Single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 2,
                            Vein360ProductId = "VEN-PV-EEPST"
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter.jpg",
                            IsDeleted = false,
                            Name = "Visions 014 Platinum Catheter (Sterile Single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 2,
                            Vein360ProductId = "VEN-PV-014P"
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "basic-procedure-pack.jpg",
                            IsDeleted = false,
                            Name = "Sterile case of 10 ClosureFast CF7-7-60 catheters: 7cm heating length x 60cm insertable length",
                            Price = 1500m,
                            Trade = 2,
                            Type = 1,
                            Vein360ProductId = "VEN-7-60B"
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-eagle-eye-platinum-catheter.jpg",
                            IsDeleted = false,
                            Name = "Sterile case of 10 ClosureFast CF7-7-100 catheters: 7cm heating length x 100cm insertable length",
                            Price = 1500m,
                            Trade = 2,
                            Type = 1,
                            Vein360ProductId = "VEN-7-100B"
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "complete-procedure-pack-7f-x-7-cm-introducer-kit.jpg",
                            IsDeleted = false,
                            Name = "Sterile case of 10 ClosureFast CF7-3-60 catheters: 3cm heating length x 60cm insertable length",
                            Price = 1500m,
                            Trade = 2,
                            Type = 1,
                            Vein360ProductId = "VEN-3-60B"
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "7F-x-7-cm-Introducer-Sheath-Kit.jpg",
                            IsDeleted = false,
                            Name = "Merit Medical Basic Procedure Pack (single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 5,
                            Vein360ProductId = "VEN-10142S"
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter.jpg",
                            IsDeleted = false,
                            Name = "Merit Medical Premium Procedure Pack (single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 5,
                            Vein360ProductId = "VEN-10144S"
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "basic-procedure-pack.jpg",
                            IsDeleted = false,
                            Name = "Merit Medical Complete Pack (w/ 7/11 introducer sheath) (single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 5,
                            Vein360ProductId = "VEN-10152S"
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-eagle-eye-platinum-catheter.jpg",
                            IsDeleted = false,
                            Name = "Merit Procedure Pack Complete with Introducer Sheath 7Fx7cm w (single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 5,
                            Vein360ProductId = "VEN-10165S"
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "complete-procedure-pack-7f-x-7-cm-introducer-kit.jpg",
                            IsDeleted = false,
                            Name = "Introducer Sheath K15-00201 (single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 4,
                            Vein360ProductId = "VEN-10130S"
                        },
                        new
                        {
                            Id = 42,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "7F-x-7-cm-Introducer-Sheath-Kit.jpg",
                            IsDeleted = false,
                            Name = "Introducer Sheath 7Fx11cm with Stainless (single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 4,
                            Vein360ProductId = "VEN-10147S"
                        },
                        new
                        {
                            Id = 43,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Image = "reprocessed-closurefast-catheter.jpg",
                            IsDeleted = false,
                            Name = "7Fx7 Introducer Sheath 0.018 SS with Echo Needle (single)",
                            Price = 1500m,
                            Trade = 2,
                            Type = 4,
                            Vein360ProductId = "VEN-10171S"
                        });
                });

            modelBuilder.Entity("Vein360.Domain.Entities.ShippingLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("TrackingNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.ToTable("ShippingLabels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543211L,
                            Used = false
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543212L,
                            Used = false
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543213L,
                            Used = false
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543214L,
                            Used = false
                        },
                        new
                        {
                            Id = 5,
                            ClinicId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543215L,
                            Used = false
                        },
                        new
                        {
                            Id = 6,
                            ClinicId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543216L,
                            Used = false
                        },
                        new
                        {
                            Id = 7,
                            ClinicId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543217L,
                            Used = false
                        },
                        new
                        {
                            Id = 8,
                            ClinicId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543218L,
                            Used = false
                        },
                        new
                        {
                            Id = 9,
                            ClinicId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543219L,
                            Used = false
                        },
                        new
                        {
                            Id = 10,
                            ClinicId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            TrackingNumber = 9876543220L,
                            Used = false
                        });
                });

            modelBuilder.Entity("Vein360.Domain.Entities.UserProductRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UseSalesCredit")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProductRates");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Vein360Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Vein360Containers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContainerCode = "CNT100001",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            ContainerCode = "CNT100002",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            ContainerCode = "CNT100003",
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            ContainerCode = "CNT100004",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            ContainerCode = "CNT100005",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            ContainerCode = "CNT100006",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            ContainerCode = "CNT100007",
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            ContainerCode = "CNT100008",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            ContainerCode = "CNT100009",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            ContainerCode = "CNT100010",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 11,
                            ContainerCode = "CNT100011",
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 12,
                            ContainerCode = "CNT100012",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 13,
                            ContainerCode = "CNT100013",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            ContainerCode = "CNT100014",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            ContainerCode = "CNT100015",
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            ContainerCode = "CNT100016",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Vein360ContainerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstimatedWeight")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Vein360ContainerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            EstimatedWeight = 6,
                            Height = 12,
                            IsDeleted = false,
                            Length = 14,
                            Name = "Vein360 Kit",
                            Width = 11
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            EstimatedWeight = 10,
                            IsDeleted = false,
                            Name = "Customer Shipper"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            EstimatedWeight = 20,
                            Height = 8,
                            IsDeleted = false,
                            Length = 24,
                            Name = "Urology Kit",
                            Width = 18
                        });
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Vein360User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("FirstTimeLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApiUser")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBuyer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDonor")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Vein360CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Vein360Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            FirstTimeLogin = true,
                            IsAdmin = true,
                            IsApiUser = false,
                            IsBuyer = false,
                            IsDeleted = false,
                            IsDonor = true,
                            Name = "Chanchal Kumar",
                            Password = "AQAAAAIAAYagAAAAEAws2AnjTEGbr+kBOKLA6qybchEzxQaAyJcdMDkIdeT3lopkhRdv4RYFKiIdaVid3g==",
                            Username = "chanchalagnihotri1987@gmail.com",
                            Vein360CustomerId = 0
                        });
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Clinic", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Vein360User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Donation", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vein360.Domain.Entities.Vein360User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.DonationContainer", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vein360.Domain.Entities.Vein360ContainerType", "ContainerType")
                        .WithMany()
                        .HasForeignKey("ContainerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vein360.Domain.Entities.Vein360User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("ContainerType");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.DonationPayment", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.DonationProduct", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Donation", "Donation")
                        .WithMany("Products")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vein360.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.DonorPreference", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("DefaultClinicId");

                    b.HasOne("Vein360.Domain.Entities.Vein360User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vein360.Domain.Entities.Vein360User", null)
                        .WithMany("DonorPreferences")
                        .HasForeignKey("Vein360UserId");

                    b.Navigation("Clinic");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Order", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vein360.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vein360.Domain.Entities.Vein360User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.ShippingLabel", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.UserProductRate", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vein360.Domain.Entities.Vein360User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Vein360Container", b =>
                {
                    b.HasOne("Vein360.Domain.Entities.Vein360ContainerType", "ContainerType")
                        .WithMany()
                        .HasForeignKey("ContainerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContainerType");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Donation", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Vein360.Domain.Entities.Vein360User", b =>
                {
                    b.Navigation("DonorPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
