// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vein360.Persistence;

#nullable disable

namespace Vein360.Persistence.Migrations
{
    [DbContext(typeof(Vein360Context))]
    [Migration("20250505101255_Iniital_Create")]
    partial class Iniital_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vien360.Domain.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DonationContainerId")
                        .HasColumnType("int");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int?>("FedexContainerId")
                        .HasColumnType("int");

                    b.Property<string>("FedexTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabelFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MasterTrackingNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("TrackingNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationContainerId");

                    b.HasIndex("DonorId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContainerType = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonationContainerId = 4,
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 2,
                            TrackingNumber = 1234567890L,
                            Weight = 10
                        },
                        new
                        {
                            Id = 2,
                            ContainerType = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonationContainerId = 9,
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 3,
                            TrackingNumber = 1234567891L,
                            Weight = 20
                        },
                        new
                        {
                            Id = 3,
                            ContainerType = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonationContainerId = 10,
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 4,
                            TrackingNumber = 1234567891L,
                            Weight = 30
                        },
                        new
                        {
                            Id = 4,
                            ContainerType = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonationContainerId = 11,
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 5,
                            TrackingNumber = 1234567891L,
                            Weight = 40
                        },
                        new
                        {
                            Id = 5,
                            ContainerType = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonationContainerId = 8,
                            DonorId = 1,
                            IsDeleted = false,
                            LabelFileName = "label.pdf",
                            Status = 1,
                            TrackingNumber = 1234567891L,
                            Weight = 50
                        });
                });

            modelBuilder.Entity("Vien360.Domain.Entities.DonationContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContainerId")
                        .HasColumnType("int");

                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("TrackingNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("DonorId");

                    b.ToTable("DonationContainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ContainerId = 2,
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 2,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 3,
                            ContainerId = 3,
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 3,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 4,
                            ContainerId = 4,
                            ContainerTypeId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 6,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 5,
                            ContainerId = 5,
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 5,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 6,
                            ContainerId = 5,
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 5,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 7,
                            ContainerId = 5,
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 5,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 8,
                            ContainerId = 8,
                            ContainerTypeId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 5,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 9,
                            ContainerId = 9,
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 4,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 10,
                            ContainerId = 10,
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 4,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 11,
                            ContainerId = 11,
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 4,
                            TrackingNumber = 794971829663L
                        },
                        new
                        {
                            Id = 12,
                            ContainerId = 12,
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            DonorId = 1,
                            IsDeleted = false,
                            Status = 4,
                            TrackingNumber = 794971829663L
                        });
                });

            modelBuilder.Entity("Vien360.Domain.Entities.DonationProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.HasIndex("ProductId");

                    b.ToTable("DonationProduct");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonationId = 1,
                            ProductId = 1,
                            Units = 1
                        },
                        new
                        {
                            Id = 2,
                            DonationId = 1,
                            ProductId = 2,
                            Units = 1
                        },
                        new
                        {
                            Id = 3,
                            DonationId = 1,
                            ProductId = 3,
                            Units = 1
                        },
                        new
                        {
                            Id = 4,
                            DonationId = 2,
                            ProductId = 1,
                            Units = 1
                        },
                        new
                        {
                            Id = 5,
                            DonationId = 2,
                            ProductId = 3,
                            Units = 1
                        },
                        new
                        {
                            Id = 6,
                            DonationId = 2,
                            ProductId = 5,
                            Units = 1
                        },
                        new
                        {
                            Id = 7,
                            DonationId = 3,
                            ProductId = 1,
                            Units = 1
                        },
                        new
                        {
                            Id = 8,
                            DonationId = 3,
                            ProductId = 4,
                            Units = 1
                        },
                        new
                        {
                            Id = 9,
                            DonationId = 3,
                            ProductId = 5,
                            Units = 1
                        },
                        new
                        {
                            Id = 10,
                            DonationId = 4,
                            ProductId = 1,
                            Units = 1
                        },
                        new
                        {
                            Id = 11,
                            DonationId = 4,
                            ProductId = 5,
                            Units = 1
                        },
                        new
                        {
                            Id = 12,
                            DonationId = 4,
                            ProductId = 2,
                            Units = 1
                        },
                        new
                        {
                            Id = 13,
                            DonationId = 5,
                            ProductId = 1,
                            Units = 1
                        },
                        new
                        {
                            Id = 14,
                            DonationId = 5,
                            ProductId = 2,
                            Units = 1
                        },
                        new
                        {
                            Id = 15,
                            DonationId = 5,
                            ProductId = 4,
                            Units = 1
                        });
                });

            modelBuilder.Entity("Vien360.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Description = "Description1",
                            Image = "ven-7-60b.jpg",
                            IsDeleted = false,
                            Name = "Vein360 Reprocessed ClosureFast Catheter (VEN-7-60B)",
                            Price = 1000m,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Description = "Description2",
                            Image = "introducerkit.jpg",
                            IsDeleted = false,
                            Name = "Vein360 Complete Procedure Pack - 7F x 7 cm Introducer Kit",
                            Price = 1800m,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Description = "Description2",
                            Image = "sheathkit.jpg",
                            IsDeleted = false,
                            Name = "Vein360 7F x 7 cm Introducer Sheath Kit",
                            Price = 900m,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Description = "Description2",
                            Image = "procedurepack.jpg",
                            IsDeleted = false,
                            Name = "Vein360 Basic Procedure Pack",
                            Price = 2000m,
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Description = "Description2",
                            Image = "ven-7-80b.jpg",
                            IsDeleted = false,
                            Name = "Vein360 Reprocessed ClosureFast Catheter (VEN-7-80B)",
                            Price = 1200m,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Description = "Description2",
                            Image = "ven-7-100b.jpg",
                            IsDeleted = false,
                            Name = "Vein360 Reprocessed ClosureFast Catheter (VEN-7-100B)",
                            Price = 1500m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Vien360.Domain.Entities.Vein360Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Vein360Containers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContainerCode = "CNT100001",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            ContainerCode = "CNT100002",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            ContainerCode = "CNT100003",
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            ContainerCode = "CNT100004",
                            ContainerTypeId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            ContainerCode = "CNT100005",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            ContainerCode = "CNT100006",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            ContainerCode = "CNT100007",
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            ContainerCode = "CNT100008",
                            ContainerTypeId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            ContainerCode = "CNT100009",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            ContainerCode = "CNT100010",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 11,
                            ContainerCode = "CNT100011",
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 12,
                            ContainerCode = "CNT100012",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 13,
                            ContainerCode = "CNT100013",
                            ContainerTypeId = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            ContainerCode = "CNT100014",
                            ContainerTypeId = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            ContainerCode = "CNT100015",
                            ContainerTypeId = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            ContainerCode = "CNT100016",
                            ContainerTypeId = 4,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Vien360.Domain.Entities.Vein360ContainerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Vien360ContainerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Name = "Large Container"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 7,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Name = "Medium Container"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Name = "Small Container"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 15,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            IsDeleted = false,
                            Name = "Extra Large Container"
                        });
                });

            modelBuilder.Entity("Vien360.Domain.Entities.Vein360User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Vein360Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 30, 0, 0)),
                            Email = "chanchalagnihotri1987@gmail.com",
                            IsDeleted = false,
                            Password = "chanchal"
                        });
                });

            modelBuilder.Entity("Vien360.Domain.Entities.Donation", b =>
                {
                    b.HasOne("Vien360.Domain.Entities.DonationContainer", "DonationContainer")
                        .WithMany()
                        .HasForeignKey("DonationContainerId");

                    b.HasOne("Vien360.Domain.Entities.Vein360User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonationContainer");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Vien360.Domain.Entities.DonationContainer", b =>
                {
                    b.HasOne("Vien360.Domain.Entities.Vein360Container", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId");

                    b.HasOne("Vien360.Domain.Entities.Vein360ContainerType", "ContainerType")
                        .WithMany()
                        .HasForeignKey("ContainerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vien360.Domain.Entities.Vein360User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("ContainerType");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Vien360.Domain.Entities.DonationProduct", b =>
                {
                    b.HasOne("Vien360.Domain.Entities.Donation", "Donation")
                        .WithMany("Products")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vien360.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Vien360.Domain.Entities.Vein360Container", b =>
                {
                    b.HasOne("Vien360.Domain.Entities.Vein360ContainerType", "ContainerType")
                        .WithMany()
                        .HasForeignKey("ContainerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContainerType");
                });

            modelBuilder.Entity("Vien360.Domain.Entities.Donation", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
